wandb_version: 1

debug:
  desc: null
  value: false
dataset:
  desc: null
  value: shd
datasets_path:
  desc: null
  value: Datasets/SHD
seed:
  desc: null
  value: 0
model_type:
  desc: null
  value: snn_delays
time_step:
  desc: null
  value: 10
n_bins:
  desc: null
  value: 5
epochs:
  desc: null
  value: 150
batch_size:
  desc: null
  value: 256
spiking_neuron_type:
  desc: null
  value: lif
init_tau:
  desc: null
  value: 1.0050000001000001
stateful_synapse_tau:
  desc: null
  value: 1.0000000001
stateful_synapse:
  desc: null
  value: false
stateful_synapse_learnable:
  desc: null
  value: false
n_inputs:
  desc: null
  value: 140
n_hidden_layers:
  desc: null
  value: 2
n_hidden_neurons:
  desc: null
  value: 256
n_outputs:
  desc: null
  value: 20
sparsity_p:
  desc: null
  value: 0
dropout_p:
  desc: null
  value: 0.4
use_batchnorm:
  desc: null
  value: true
bias:
  desc: null
  value: false
detach_reset:
  desc: null
  value: true
loss:
  desc: null
  value: sum
loss_fn:
  desc: null
  value: CEloss
output_v_threshold:
  desc: null
  value: 1000000000.0
v_threshold:
  desc: null
  value: 1.0
alpha:
  desc: null
  value: 5.0
surrogate_function:
  desc: null
  value: ATan(alpha=5.0, spiking=True)
init_w_method:
  desc: null
  value: kaiming_uniform
optimizer_w:
  desc: null
  value: adam
optimizer_pos:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 1.0e-05
lr_w:
  desc: null
  value: 0.001
lr_pos:
  desc: null
  value: 0.1
scheduler_w:
  desc: null
  value: one_cycle
scheduler_pos:
  desc: null
  value: cosine_a
max_lr_w:
  desc: null
  value: 0.005
max_lr_pos:
  desc: null
  value: 0.5
t_max_w:
  desc: null
  value: 150
t_max_pos:
  desc: null
  value: 150
DCLSversion:
  desc: null
  value: gauss
decrease_sig_method:
  desc: null
  value: exp
kernel_count:
  desc: null
  value: 1
max_delay:
  desc: null
  value: 25
sigInit:
  desc: null
  value: 12
final_epoch:
  desc: null
  value: 37
left_padding:
  desc: null
  value: 24
right_padding:
  desc: null
  value: 12
init_pos_method:
  desc: null
  value: uniform
init_pos_a:
  desc: null
  value: -13
init_pos_b:
  desc: null
  value: 12
lr_w_finetuning:
  desc: null
  value: 0.0001
max_lr_w_finetuning:
  desc: null
  value: 0.00012
dropout_p_finetuning:
  desc: null
  value: 0
stateful_synapse_learnable_finetuning:
  desc: null
  value: false
spiking_neuron_type_finetuning:
  desc: null
  value: lif
epochs_finetuning:
  desc: null
  value: 30
augment:
  desc: null
  value: false
rnoise_sig:
  desc: null
  value: 0
TN_mask_aug_proba:
  desc: null
  value: 0.65
time_mask_size:
  desc: null
  value: 8
neuron_mask_size:
  desc: null
  value: 28
cutmix_aug_proba:
  desc: null
  value: 0.5
use_wandb:
  desc: null
  value: true
wandb_token:
  desc: null
  value: 82eefce4f8013b02630c61cf2d19ef4bcb0a80b4
wandb_project_name:
  desc: null
  value: SNN_Delays
run_name:
  desc: null
  value: Test_Run_5
run_info:
  desc: null
  value: '||snn_delays||shd||10ms||bins=5'
wandb_run_name:
  desc: null
  value: Test_Run_5
wandb_group_name:
  desc: null
  value: Test_Run_5||snn_delays||shd||10ms||bins=5
save_model_path:
  desc: null
  value: Test_Run_5.pt
wandb_run_name_finetuning:
  desc: null
  value: Test_Run_5
wandb_group_name_finetuning:
  desc: null
  value: Test_Run_5||snn_delays||shd||10ms||bins=5
save_model_path_finetuning:
  desc: null
  value: Test_Run_5.pt
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1690824451.141639
    t:
      1:
      - 1
      - 41
      - 51
      - 55
      2:
      - 1
      - 41
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.15.7
      8:
      - 3
      - 5
